name: Create Production Builds

jobs:
  build_android:
    type: build # This job type creates a production build for Android
    params:
      platform: android
      ref: master
  build_ios:
    type: build # This job type creates a production build for iOS
    params:
      platform: ios
      ref: master
