# Generated by Django 5.2.7 on 2026-01-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_add_user_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("FUEL", "Fuel"),
                    ("DATA", "Data"),
                    ("FOOD", "Food"),
                    ("REPAIRS", "Repairs"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
