# Generated by Django 5.2.7 on 2026-01-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_transaction_bonuses_transaction_gross_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="department",
            field=models.CharField(
                choices=[
                    ("INVESTMENT", "Investment"),
                    ("REVENUE", "Revenue"),
                    ("OTHER", "Other"),
                ],
                default="REVENUE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
