# Generated by Django 5.2.7 on 2026-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0005_transaction_department_alter_expense_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("FUEL", "Fuel"),
                    ("DATA", "Data"),
                    ("FOOD", "Food"),
                    ("REPAIRS", "Repairs"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="platform",
            field=models.CharField(
                choices=[("YANGO", "Yango"), ("BOLT", "Bolt"), ("PRIVATE", "Private")],
                db_index=True,
                default="YANGO",
                max_length=10,
            ),
        ),
    ]
