# Generated by Django 5.2.7 on 2026-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0006_alter_expense_category_alter_expense_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tip_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
